### ISSUE TITLE
Docker services not reachable inside liunux cluster

### ISSUE THREAD

**Issue by jfalameda** [microsoft/service-fabric#1089]
Hi,

I deployed an app with multiple docker services on a SF linux cluster via docker-compose. Although I specified aliases and hostname on the docker compose, I cannot reach those services (from other docker services) using DNS resolution. Why is this happening? How would service discovery work in this case?

```
patient:
    ...
    ports:
      - "5010:5010"
    hostname: patient.dhcloud
    networks:
       default:    
          aliases:
           - patient.dhcloud
```

---
Assignees: /cc @microsoft/service-fabric-triage
