### ISSUE TITLE
Service name resolution fails in multi-container (windows) app

### ISSUE THREAD

**Issue by rn-3** [microsoft/service-fabric#788]
Call to other services are failing since the service name could not be resolved in an application setup that's composed of 3 different windows containers. 
SF on a local Standalone Cluster version **6.1.467.9494**. 
Host OS & the Container Guest OS are both - **Microsoft Windows [Version 10.0.14393]**.

This SF App is created using docker compose file.

**Compose File:**
```
version: '3'
services:
  svc1.app1:
    image: image1
    expose:
      - "2828"
    build:
      context: ./SS
      dockerfile: Dockerfile
  svc2.app1:
    image: image2
    depends_on:
      - svc1.app1
    expose:
      - "2880"
    links:
      - svc1.app1
    build:
      context: ./CS
      dockerfile: Dockerfile
  svc3.app1:
    image: image3
    depends_on:
      - svc1.app1
      - svc2.app1
    expose:
      - "80"
    links:
      - svc1.app1
      - svc2.app1
    build:
      context: ./PS
      dockerfile: Dockerfile
networks:
  default:
    external:
      name: nat

```

Error received by a web app running in svc3 while trying to connect to svc1 :
There was no endpoint listening at `http://svc1.app1:2828/CSS` that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.

Looking at a similar issue that is closed: [https://github.com/Azure/service-fabric-issues/issues/332](url)

**nslookup against 127.0.0.1** returns an empty result for my service name, rather than a non-existent domain error. 

Here's the output from: `nslookup -type=any <service.app> 127.0.0.1`

```
nslookup -type=any cepserver.multicontainercep 127.0.0.1
Server:  localhost
Address:  127.0.0.1

cepserver.multicontainercep     text =

        "cepserver.multicontainercepType:7d7d3b7e-8590-48a8-82a9-6823ea358045:131690664419887247"
cepserver.multicontainercep     SRV service location:
          priority       = 0
          weight         = 0
          port           = 7
          svr hostname   = cepserver.multicontainercepType
(root)  ??? unknown type 41 ???

```
